import React, { useState } from 'react';

const HistoryPanel = ({ requests, onLoadRequest, onClearHistory, settings }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterMethod, setFilterMethod] = useState('ALL');

  const filteredRequests = requests.filter(request => {
    const matchesSearch = request.url.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         request.method.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesMethod = filterMethod === 'ALL' || request.method === filterMethod;
    return matchesSearch && matchesMethod;
  });

  const getStatusColor = (status) => {
    if (!status) return 'default';
    if (status >= 200 && status < 300) return 'success';
    if (status >= 300 && status < 400) return 'warning';
    if (status >= 400) return 'error';
    return 'default';
  };

  const formatDate = (timestamp) => {
    return new Date(timestamp).toLocaleString();
  };

  const methods = ['ALL', 'GET', 'POST', 'PUT', 'DELETE', 'PATCH'];

  const generateDocumentation = async (request) => {
    if (!settings?.openaiApiKey) {
      alert('Please configure your OpenAI API key in Settings to generate documentation.');
      return;
    }

    try {
      // Generate documentation using OpenAI
      const documentation = await generateAPIDocumentation(request, settings.openaiApiKey);
      
      // Create and download the file
      downloadDocumentation(documentation, request);
    } catch (error) {
      console.error('Failed to generate documentation:', error);
      alert('Failed to generate documentation. Please check your OpenAI API key and try again.');
    }
  };

  const generateAPIDocumentation = async (request, apiKey) => {
    const prompt = `Generate comprehensive API documentation for the following HTTP request. Make it professional and detailed:

**Request Details:**
- Method: ${request.method}
- URL: ${request.url}
- Headers: ${JSON.stringify(request.headers || {}, null, 2)}
- Parameters: ${JSON.stringify(request.params || [], null, 2)}
- Body: ${request.body || 'None'}
- Form Data: ${JSON.stringify(request.formData || [], null, 2)}

**Response Details:**
- Status: ${request.response?.status || 'N/A'}
- Response Time: ${request.response?.responseTime || 'N/A'}ms
- Response Data: ${JSON.stringify(request.response?.data || {}, null, 2)}

Please create documentation that includes:
1. API Endpoint Overview
2. Request Format
3. Parameters Description
4. Headers Description
5. Request Body/Payload
6. Response Format
7. Example Usage
8. Error Handling
9. Notes and Best Practices

Format it as clean, readable documentation that could be used by developers.`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: 'You are a technical documentation expert. Generate clear, comprehensive API documentation.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        max_tokens: 2000,
        temperature: 0.3
      })
    });

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.status}`);
    }

    const data = await response.json();
    return data.choices[0].message.content;
  };

  const downloadDocumentation = (documentation, request) => {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `API_Documentation_${request.method}_${timestamp}.txt`;
    
    const content = `# API Documentation
Generated on: ${new Date().toLocaleString()}
Generated by: PostExt Chrome Extension

${documentation}

---
Generated from request data:
${JSON.stringify(request, null, 2)}
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="history-panel">
      <div className="history-header">
        <h3>📚 Request History</h3>
        <div className="history-controls">
          <input
            type="text"
            className="search-input"
            placeholder="Search requests..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
          <select
            className="filter-select"
            value={filterMethod}
            onChange={(e) => setFilterMethod(e.target.value)}
          >
            {methods.map(method => (
              <option key={method} value={method}>{method}</option>
            ))}
          </select>
          <button
            className="clear-btn"
            onClick={onClearHistory}
            disabled={requests.length === 0}
          >
            🗑️ Clear All
          </button>
        </div>
      </div>

      <div className="history-stats">
        <div className="stat-item">
          <strong>Total:</strong> {requests.length}
        </div>
        <div className="stat-item">
          <strong>Filtered:</strong> {filteredRequests.length}
        </div>
        <div className="stat-item">
          <strong>Success Rate:</strong> {
            requests.length > 0 
              ? Math.round((requests.filter(r => r.response?.status >= 200 && r.response?.status < 300).length / requests.length) * 100)
              : 0
          }%
        </div>
      </div>

      <div className="requests-list">
        {filteredRequests.length === 0 ? (
          <div className="no-requests">
            {requests.length === 0 ? (
              <>
                <h4>📭 No Requests Yet</h4>
                <p>Your request history will appear here</p>
              </>
            ) : (
              <>
                <h4>🔍 No Matching Requests</h4>
                <p>Try adjusting your search or filter</p>
              </>
            )}
          </div>
        ) : (
          filteredRequests.map((request) => (
            <div key={request.id} className="request-item">
              <div className="request-summary">
                <div className="request-main">
                  <span className={`method-badge ${request.method.toLowerCase()}`}>
                    {request.method}
                  </span>
                  <span className="request-url" title={request.url}>
                    {request.url}
                  </span>
                  {request.response && (
                    <span className={`status-badge ${getStatusColor(request.response.status)}`}>
                      {request.response.status}
                    </span>
                  )}
                </div>
                <div className="request-meta">
                  <span className="timestamp">{formatDate(request.timestamp)}</span>
                  {request.response?.timing && (
                    <span className="timing">⏱️ {request.response.timing}ms</span>
                  )}
                </div>
              </div>
              
              <div className="request-actions">
                <button
                  className="load-btn"
                  onClick={() => onLoadRequest(request)}
                  title="Load this request"
                >
                  📂 Load
                </button>
                <button
                  className="copy-btn"
                  onClick={() => {
                    navigator.clipboard.writeText(JSON.stringify({
                      method: request.method,
                      url: request.url,
                      headers: request.headers,
                      body: request.body,
                      params: request.params,
                      formData: request.formData
                    }, null, 2));
                    alert('Request copied to clipboard!');
                  }}
                  title="Copy request"
                >
                  📋
                </button>
                <button
                  className="save-docs-btn"
                  onClick={() => generateDocumentation(request)}
                  title="Generate API documentation"
                >
                  📝 Docs
                </button>
              </div>

              {request.response && (
                <div className="response-preview">
                  <div className="response-summary">
                    <span>Response:</span>
                    {request.response.error ? (
                      <span className="error-text">❌ {request.response.message}</span>
                    ) : (
                      <span className="success-text">
                        ✅ {Object.keys(request.response.data || {}).length} keys
                      </span>
                    )}
                  </div>
                </div>
              )}
            </div>
          ))
        )}
      </div>

      {requests.length > 0 && (
        <div className="history-footer">
          <p className="footer-text">
            💡 Tip: Click "Load" to reuse any previous request
          </p>
        </div>
      )}
    </div>
  );
};

export default HistoryPanel;